[build]
builder = "nixpacks"
buildCommand = "npm install"
installCommand = "npm install --omit=dev"

[build.args]
NODE_VERSION = "22.12.0"

[deploy]
startCommand = "node index.js"
healthCheckPath = "/"
healthCheckTimeout = 60
restartPolicyType = "on_failure"

[deploy.healthCheck]
path = "/"
timeout = 60